// Strength Rebuild — program seed (v0.2 spec, §4 microcycle)
// This is only the FIRST-RUN seed. After first launch the program lives in
// localStorage and is edited in-app; changes here won't overwrite it.

const SEED_PROGRAM = {
  specVersion: '0.2',
  days: [
    {
      id: 'dayA',
      name: 'Day A',
      subtitle: 'Squat + Horizontal',
      slots: [
        {
          id: 'a1', name: 'Broad jump', pattern: 'Power',
          sets: 4, reps: [3, 3], rir: '', trackRIR: false,
          load: 'none', metric: 'reps', perSide: false, restSec: 105,
          progression: 'output', increment: 0,
          progressionNote: 'Output/distance when crisp — never to fatigue',
          cue: 'Land soft, absorb — don\'t chase distance',
        },
        {
          id: 'a2', name: 'Front squat', pattern: 'Squat main',
          sets: 4, reps: [5, 5], rir: '2–3', trackRIR: true,
          load: 'external', metric: 'reps', perSide: false, restSec: 170,
          progression: 'load', increment: 5,
          progressionNote: 'Double progression; small jumps',
          cue: 'Upright torso, full depth',
        },
        {
          id: 'a3a', name: 'DB bench press', pattern: 'Push · superset',
          sets: 3, reps: [6, 8], rir: '2–3', trackRIR: true,
          load: 'external', metric: 'reps', perSide: false, restSec: 40,
          group: '3', progression: 'load', increment: 5,
          progressionNote: 'Double progression',
          cue: 'Free the scapula',
        },
        {
          id: 'a3b', name: 'Chest-supported DB row', pattern: 'Pull · superset',
          sets: 3, reps: [8, 10], rir: '2', trackRIR: true,
          load: 'external', metric: 'reps', perSide: false, restSec: 105,
          group: '3', progression: 'load', increment: 5,
          progressionNote: 'Double progression',
          cue: 'Chest glued; lead with the shoulder blades',
        },
        {
          id: 'a4', name: 'Bulgarian split squat (RFE)', pattern: 'Single-leg',
          sets: 3, reps: [8, 10], rir: '2–3', trackRIR: true,
          load: 'external', metric: 'reps', perSide: true, restSec: 105,
          progression: 'load', increment: 5,
          progressionNote: 'Load when both sides clean; deeper knee travel',
          cue: 'Knee tracks past the toes, heel down',
        },
        {
          id: 'a5', name: 'Slider leg curl', pattern: 'Hamstring · knee-flexion',
          sets: 3, reps: [6, 8], rir: '', trackRIR: false,
          load: 'none', metric: 'reps', perSide: false, restSec: 90,
          progression: 'variation', increment: 0,
          progressionNote: 'Bilateral → slow/paused → single-leg (R first) → Nordic negatives → Nordics',
          cue: 'Slow eccentric; right side leads, rep-matched',
        },
        {
          id: 'a6', name: 'Suitcase carry', pattern: 'Carry · anti-lateral',
          sets: 3, reps: [30, 40], rir: '', trackRIR: false,
          load: 'external', metric: 'meters', perSide: true, restSec: 75,
          progression: 'load', increment: 5,
          progressionNote: 'Load first, then distance',
          cue: "Ribcage stacked, don't tip",
        },
        {
          id: 'a7', name: 'Pallof press', pattern: 'Trunk · anti-rotation',
          sets: 2, reps: [10, 12], rir: '', trackRIR: false,
          load: 'external', metric: 'reps', perSide: true, restSec: 60,
          progression: 'load', increment: 2.5,
          progressionNote: 'Heavier cable / longer lever / pause',
          cue: "Resist rotation, don't create it",
        },
        {
          id: 'a8', name: 'Active→passive hang', pattern: 'Grip · finisher',
          sets: 2, reps: [30, 45], rir: '', trackRIR: false,
          load: 'none', metric: 'seconds', perSide: false, restSec: 0,
          progression: 'variation', increment: 0,
          progressionNote: 'Time → offset → single-arm-assisted',
          cue: 'Active shoulders',
        },
      ],
    },
    {
      id: 'dayB',
      name: 'Day B',
      subtitle: 'Hinge + Vertical',
      slots: [
        {
          id: 'b1', name: 'Kettlebell swing', pattern: 'Power · hinge',
          sets: 4, reps: [6, 6], rir: '', trackRIR: false,
          load: 'external', metric: 'reps', perSide: false, restSec: 105,
          progression: 'output', increment: 0,
          progressionNote: 'Output/power when crisp — heavier bell or more snap, never to fatigue',
          cue: 'Snap the hips, float the bell — power from the hinge',
        },
        {
          id: 'b2', name: 'Trap-bar deadlift', pattern: 'Hinge main',
          sets: 4, reps: [5, 5], rir: '2–3', trackRIR: true,
          load: 'external', metric: 'reps', perSide: false, restSec: 170,
          progression: 'load', increment: 5,
          progressionNote: 'Double progression; small jumps',
          cue: 'Neutral spine, drive the floor',
        },
        {
          id: 'b3', name: 'Reverse hyper', pattern: 'Posterior',
          sets: 3, reps: [10, 15], rir: '', trackRIR: false,
          load: 'external', metric: 'reps', perSide: false, restSec: 75,
          progression: 'load', increment: 10,
          progressionNote: 'Reps → load, kept clean',
          cue: 'Glute-driven, no ballistic swing',
        },
        {
          id: 'b4a', name: 'DB standing overhead press', pattern: 'Push · superset',
          sets: 3, reps: [6, 8], rir: '2–3', trackRIR: true,
          load: 'external', metric: 'reps', perSide: false, restSec: 40,
          group: '4', progression: 'load', increment: 5,
          progressionNote: 'Double progression',
          cue: 'Ribs down, no low-back arch',
        },
        {
          id: 'b4b', name: 'Chin-up, strict', pattern: 'Pull · superset',
          sets: 3, reps: [5, 12], rir: '~2', trackRIR: true,
          load: 'added', metric: 'reps', perSide: false, restSec: 105,
          group: '4', progression: 'load', increment: 2.5,
          progressionNote: 'Reps → then add load (belt)',
          cue: 'Full dead hang, chin over',
        },
        {
          id: 'b5', name: 'Loaded cossack squat', pattern: 'Single-leg · frontal',
          sets: 3, reps: [6, 8], rir: '2–3', trackRIR: true,
          load: 'external', metric: 'reps', perSide: true, restSec: 90,
          progression: 'load', increment: 5,
          progressionNote: 'Depth/control first, then load',
          cue: 'Own the bottom, heel down',
        },
        {
          id: 'b6', name: 'Front-rack carry', pattern: 'Carry · anti-extension',
          sets: 3, reps: [30, 40], rir: '', trackRIR: false,
          load: 'external', metric: 'meters', perSide: false, restSec: 75,
          progression: 'load', increment: 5,
          progressionNote: 'Load → distance → overhead carry',
          cue: 'Ribs down, breathe behind the brace',
        },
        {
          id: 'b7', name: 'Hanging leg raise', pattern: 'Trunk · anti-extension',
          sets: 3, reps: [8, 12], rir: '', trackRIR: false,
          load: 'none', metric: 'reps', perSide: false, restSec: 60,
          progression: 'variation', increment: 0,
          progressionNote: 'Bent → straight → toes-to-bar → load',
          cue: 'Curl the pelvis first, no swing',
        },
      ],
    },
  ],
};
